### ISSUE TITLE
KiotaClientFactory is missing key helper methods in C#

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/kiota-http-dotnet#144]
Maybe I am missing something but this is painful....

A key scenario is that someone wants to use Kiota "out of the box" but with one more MessageHandler.  e.g. CompressionHandler because it isn't there by default yet.

To customize the message handling pipeline it is necessary to pass in a "custom" HttpClient. e.g.

```csharp
var requestAdapter = new HttpClientRequestAdapter(new AnonymousAuthenticationProvider(), httpClient:client);
```

You can create your own HttpClient by doing

```csharp
var client = KiotaClientFactory.Create();
```

This is great if you want to set custom headers that are sent with every request.  Having said that, if you set an Accept header it will get overridden by RequestBuilders.  That's not ideal.
However, if you want to add a message handler, you need to use the overload that accepts a messagehandler pipeline.  I'm not sure why we dropped this terminology for "chain" as pipeline has been the term used since HttpClient was originally created.

You can create a customized set of handlers by calling the `CreateDefaultHandlers` method and adjusting it. e.g.

```csharp
       var handlers = KiotaClientFactory.CreateDefaultHandlers();
        handlers.Insert(0, new CompressionHandler());
```
However, there is no obvious way to use that list.  I tried this
```csharp
var pipeline = KiotaClientFactory.ChainHandlersCollectionAndGetFirstLink(KiotaClientFactory.GetDefaultHttpMessageHandler(), handlers);
```
but unfortunately, we made `ChainHandlersCollectionAndGetFirstLink` accept "params".  I had to Bing how to use a list to provide "params".  So in the end, this works.

```csharp
        var handlers = KiotaClientFactory.CreateDefaultHandlers();
        handlers.Insert(0, new CompressionHandler());
        var pipeline = KiotaClientFactory.ChainHandlersCollectionAndGetFirstLink(KiotaClientFactory.GetDefaultHttpMessageHandler(), handlers.ToArray());
        var client = KiotaClientFactory.Create(pipeline);
        var requestAdapter = new HttpClientRequestAdapter(new AnonymousAuthenticationProvider(), httpClient:client);
````

I would like us to consider adding an overload to `Create()` that accepts a list of handlers and optionally a non-default finalhandler.  This would allow a developer to do the following.

```csharp
        var handlers = KiotaClientFactory.CreateDefaultHandlers();
        handlers.Insert(0, new CompressionHandler());
        var client = KiotaClientFactory.Create(handlers);
        var requestAdapter = new HttpClientRequestAdapter(new AnonymousAuthenticationProvider(), httpClient:client);
````
I don't see a whole lot of value making our customers convert the list to a pipeline.  We can do that as an implementation detail.

**Comment by baywet** [comment]
passing the handlers independently of the client is going to lead to overloads overload IMHO. The client may carry additional information the user wants to set besides the handlers.

As for the other languages:
- [TypeScript passes the handlers directly, but that's because it doesn't have a client object](https://github.com/microsoft/kiota-typescript/blob/37c13cdfbedd09aaee8accea22de5b5e461cc0c6/packages/http/fetch/src/httpClient.ts#L27)
- [Java is just create](https://github.com/microsoft/kiota-java/blob/f41fcfefa7eb119f1e680b0e1bca3cd36c11660b/components/http/okHttp/src/main/java/com/microsoft/kiota/http/KiotaClientFactory.java#L32) the order doesn't matter
- [Same for Go](https://github.com/microsoft/kiota-http-go/blob/b162cb63903518fdf02bd4e281e7729bcad899fc/kiota_client_factory.go#L600
- Ruby doesn't have middleware yet
- [Python doesn't require ordering](https://github.com/microsoft/kiota-http-python/blob/231b749fa2b9d03f5415db5da9a1a60d7d7fe928/kiota_http/kiota_client_factory.py#L71)
- [PHP doesn't require people to order themselves, but uses a stack which maintains order](https://github.com/microsoft/kiota-http-guzzle-php/blob/7f3ff5ba68fd6670d1ae1be77a26182584a048fd/src/KiotaClientFactory.php#L49)
